/**
 * skills-transform.test.mjs — the skills compiler's edge model (#292).
 *
 * Three things this suite pins:
 *
 *   1. MULTI-PARENT. `parent:` may name several agents. The FIRST is PRIMARY — it
 *      is the tree edge and drives breadcrumb / level / ownership / naming exactly
 *      as a single parent did before. The rest are recorded ATTACHMENTS: reported
 *      by validate/preview, with no effect on the compiled layout (which is flat).
 *      Every named parent is still validated: it must resolve, and it must be an
 *      agent.
 *   2. PRELOAD IS OPT-IN. An agent's compiled `skills:` frontmatter comes from a
 *      per-skill `preload: true`, not from attachment. Per Claude Code's subagent
 *      docs that field "controls which skills are preloaded, not which skills the
 *      subagent can access" — so it is context provisioning, and preloading a
 *      whole scope would spend the fresh context window delegation exists for. A
 *      configurable cap WARNS (never refuses) when one agent's preload set grows.
 *   3. THE LOCKOUT. `no-skills: true` on an agent compiles `disallowedTools:
 *      [Skill]` — the one real boundary the platform offers — WITHOUT touching the
 *      agent's `tools` list (an allowlist that omitted Skill would also omit
 *      everything else).
 *
 * Pure: transformAll takes plain note records; analyzeVault/previewVault run over
 * a fake SkillsSource. Nothing here imports `obsidian`.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";
import * as os from "node:os";
import * as path from "node:path";
import { transformAll, DEFAULT_PRELOAD_CAP } from "../src/kernel/skills/transform.ts";
import { analyzeVault, previewVault } from "../src/kernel/skills/exporter.ts";

const OPTS = { pluginName: "vault-skills", synthesizeRoot: false };

/** A note record as the collector hands it to the transform. */
function note(pathname, frontmatter, body = "body", parentPaths = []) {
  return { path: pathname, frontmatter, body, parentPaths };
}

const agent = (p, fm = {}, parents = []) => note(p, { type: "agent", ...fm }, `${p} body`, parents);
const skill = (p, fm = {}, parents = []) => note(p, { type: "skill", ...fm }, `${p} body`, parents);

function compile(notes, opts = {}) {
  return transformAll(notes, { ...OPTS, ...opts });
}

/** The compiled file for a generated name (agents/<name>.md, skills/<name>/SKILL.md). */
function fileFor(result, relOut) {
  const g = result.generated.find((x) => x.relOut === relOut);
  assert.ok(g, `no generated file at ${relOut} (have: ${result.generated.map((x) => x.relOut).join(", ")})`);
  return g.content;
}

/** The frontmatter block of a compiled file, as text. */
function frontmatterOf(content) {
  const m = /^---\n([\s\S]*?)\n---/.exec(content);
  assert.ok(m, "no frontmatter block");
  return m[1];
}

// ── 1. single-parent regression ─────────────────────────────────────────────

describe("single-parent trees compile exactly as before", () => {
  // Root agent → scope agent → skill. The skill opts into preloading, which is
  // how a vault reproduces the pre-#292 "attached ⇒ preloaded" output.
  const vault = () => [
    agent("Root.md", { root: true, label: "Vault", description: "root agent" }),
    agent("Scope.md", { label: "Scope", description: "scope agent" }, ["Root.md"]),
    skill("Doer.md", { description: "does the thing", preload: true }, ["Scope.md"]),
  ];

  test("the compiled agent file is byte-for-byte the pre-#292 shape", () => {
    const r = compile(vault());
    assert.deepEqual(r.errors, []);
    assert.deepEqual(r.warnings, []);
    assert.equal(
      fileFor(r, "agents/scope.md"),
      [
        "---",
        "name: scope",
        "description: scope agent",
        "skills:",
        '  - "vault-skills:doer"',
        "---",
        "",
        "<!-- generated by obsidian-vault-skills from vault note: Scope.md",
        "     Do not edit here — edit the source note and re-export. -->",
        "",
        "Scope.md body",
        "",
        "## Skills",
        "",
        "These scope skills are preloaded into your context — use them for work in this scope: `vault-skills:doer`.",
        "",
      ].join("\n"),
    );
  });

  test("the compiled skill file is unchanged — `preload` is a compiler directive, not SKILL.md frontmatter", () => {
    const r = compile(vault());
    const fm = frontmatterOf(fileFor(r, "skills/doer/SKILL.md"));
    assert.equal(fm, 'name: doer\ndescription: "[Scope] does the thing"');
    assert.ok(!/preload/.test(fileFor(r, "skills/doer/SKILL.md")), "`preload` must not leak into the emitted skill");
  });

  test("tree/level/breadcrumb/naming semantics are untouched, and the new tree fields are OMITTED when empty", () => {
    const r = compile(vault());
    assert.deepEqual(r.tree.find((n) => n.name === "scope"), {
      name: "scope", kind: "agent", parent: "root", level: 1,
      skills: ["doer"], children: [], crosscutting: false,
    });
    assert.deepEqual(r.tree.find((n) => n.name === "doer"), {
      name: "doer", kind: "skill", parent: "scope", level: 2,
      skills: [], children: [], crosscutting: false, preload: true,
    });
    assert.deepEqual(r.attachments, []);
    assert.deepEqual(r.preloads, [{ agent: "scope", path: "Scope.md", skills: ["vault-skills:doer"], overCap: false }]);
    assert.equal(r.preloadCap, DEFAULT_PRELOAD_CAP);
  });

  test("an unresolved or non-agent single parent still errors with the same message", () => {
    const missing = compile([agent("Root.md", { root: true }), skill("S.md", {}, ["Ghost.md"])]);
    assert.deepEqual(missing.errors, ["S.md: unresolved parent Ghost.md"]);
    const notAgent = compile([agent("Root.md", { root: true }), skill("A.md", {}, ["Root.md"]), skill("S.md", {}, ["A.md"])]);
    assert.deepEqual(notAgent.errors, ["S.md: parent is not an agent"]);
  });
});

// ── 2. multi-parent: primary + attachments ──────────────────────────────────

describe("multi-parent: the first parent is primary, the rest are attachments", () => {
  const vault = (skillFm = {}) => [
    agent("Root.md", { root: true, label: "Vault" }),
    agent("Alpha.md", { label: "Alpha" }, ["Root.md"]),
    agent("Beta.md", { label: "Beta" }, ["Root.md"]),
    skill("Shared.md", { description: "shared skill", ...skillFm }, ["Alpha.md", "Beta.md"]),
  ];

  test("no error: the strict-single-parent refusal is gone", () => {
    const r = compile(vault());
    assert.deepEqual(r.errors, []);
    assert.ok(!r.warnings.some((w) => /single-parent/.test(w)));
  });

  test("the PRIMARY parent alone drives tree position, level and breadcrumb", () => {
    const r = compile(vault());
    const node = r.tree.find((n) => n.name === "shared");
    assert.equal(node.parent, "alpha");
    assert.equal(node.level, 2);
    assert.deepEqual(node.extraParents, ["beta"]);
    // Breadcrumb comes from the primary chain only — Beta is nowhere in it.
    assert.match(fileFor(r, "skills/shared/SKILL.md"), /description: "\[Alpha\] shared skill"/);
    // Ownership (the tree edge) stays with the primary; Beta records an attachment.
    assert.deepEqual(r.tree.find((n) => n.name === "alpha").skills, ["shared"]);
    assert.deepEqual(r.tree.find((n) => n.name === "beta").skills, []);
    assert.deepEqual(r.tree.find((n) => n.name === "beta").attached, ["shared"]);
  });

  test("the output stays FLAT — one SKILL.md, whatever it is attached to", () => {
    const r = compile(vault());
    assert.deepEqual(
      r.generated.map((g) => g.relOut).filter((p) => p.startsWith("skills/")),
      ["skills/shared/SKILL.md"],
    );
  });

  test("attachments are reported: primary, extra, and the preload flag", () => {
    const r = compile(vault({ preload: true }));
    assert.deepEqual(r.attachments, [
      { name: "shared", kind: "skill", path: "Shared.md", primary: "alpha", extra: ["beta"], preload: true },
    ]);
  });

  test("EVERY named parent is validated: an unresolved extra parent is an error and nothing is emitted", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", {}, ["Root.md"]),
      skill("Shared.md", {}, ["Alpha.md", "Ghost.md"]),
    ]);
    assert.deepEqual(r.errors, ["Shared.md: unresolved parent Ghost.md"]);
    assert.ok(!r.generated.some((g) => g.relOut.startsWith("skills/shared")));
  });

  test("EVERY named parent is validated: a non-agent extra parent is an error", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", {}, ["Root.md"]),
      skill("Other.md", {}, ["Alpha.md"]),
      skill("Shared.md", {}, ["Alpha.md", "Other.md"]),
    ]);
    assert.deepEqual(r.errors, ["Shared.md: parent Other.md is not an agent"]);
  });

  test("a note naming itself as a parent is an error", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", {}, ["Root.md", "Alpha.md"]),
    ]);
    assert.deepEqual(r.errors, ["Alpha.md: names itself as a parent"]);
  });

  test("the same parent listed twice warns and attaches once", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", {}, ["Root.md"]),
      skill("Shared.md", {}, ["Alpha.md", "Alpha.md"]),
    ]);
    assert.deepEqual(r.errors, []);
    assert.deepEqual(r.warnings, ["Shared.md: parent Alpha.md listed twice — the duplicate is ignored"]);
    assert.deepEqual(r.attachments, []);
    assert.deepEqual(r.tree.find((n) => n.name === "alpha").skills, ["shared"]);
  });

  test("an attachment to an INVALID agent is dropped with a warning, not cascaded into an error", () => {
    // Two declared roots: the second is refused, so Beta never becomes a valid agent.
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", {}, ["Root.md"]),
      agent("Beta.md", { root: true }),
      skill("Shared.md", {}, ["Alpha.md", "Beta.md"]),
    ]);
    assert.deepEqual(r.errors, ["Beta.md: multiple roots; ignoring this one"]);
    assert.deepEqual(r.warnings, ["Shared.md: attached parent Beta.md is invalid — attachment ignored"]);
    // The skill itself still compiles under its primary parent.
    assert.ok(r.generated.some((g) => g.relOut === "skills/shared/SKILL.md"));
    assert.deepEqual(r.attachments, []);
  });

  test("a policy still takes exactly one parent (its parent is a lineage edge, not an attachment)", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", {}, ["Root.md"]),
      note("P.md", { type: "policy" }, "policy body", ["Root.md", "Alpha.md"]),
    ]);
    assert.deepEqual(r.errors, ["P.md: policy has multiple parents (strict single-parent)"]);
  });
});

// ── 3. preload: opt-in, attachment-wide, capped ─────────────────────────────

describe("preload compilation is opt-in and follows attachment", () => {
  test("an opted-in skill is preloaded into EVERY agent it is attached to (primary and extra)", () => {
    const r = compile([
      agent("Root.md", { root: true, label: "Vault" }),
      agent("Alpha.md", { label: "Alpha" }, ["Root.md"]),
      agent("Beta.md", { label: "Beta" }, ["Root.md"]),
      skill("Shared.md", { preload: true }, ["Alpha.md", "Beta.md"]),
    ]);
    assert.match(frontmatterOf(fileFor(r, "agents/alpha.md")), /^skills:\n  - "vault-skills:shared"$/m);
    assert.match(frontmatterOf(fileFor(r, "agents/beta.md")), /^skills:\n  - "vault-skills:shared"$/m);
    assert.deepEqual(r.preloads.map((p) => p.agent).sort(), ["alpha", "beta"]);
  });

  test("an attached skill that did NOT opt in produces no `skills:` key — it stays discoverable via the Skill tool", () => {
    const r = compile([
      agent("Root.md", { root: true, label: "Vault" }),
      agent("Alpha.md", { label: "Alpha" }, ["Root.md"]),
      skill("Quiet.md", {}, ["Alpha.md"]),
    ]);
    const content = fileFor(r, "agents/alpha.md");
    assert.ok(!/^skills:/m.test(frontmatterOf(content)), "an agent with no opted-in attachments must carry no skills key");
    assert.match(content, /attached to you but not preloaded — invoke them with the Skill tool[^\n]*`vault-skills:quiet`/);
    assert.deepEqual(r.preloads, []);
  });

  test("an agent with no attached skills at all gets neither the key nor the section", () => {
    const r = compile([
      agent("Root.md", { root: true, label: "Vault" }),
      agent("Alpha.md", { label: "Alpha" }, ["Root.md"]),
    ]);
    const content = fileFor(r, "agents/alpha.md");
    assert.ok(!/^skills:/m.test(frontmatterOf(content)));
    assert.ok(!/## Skills/.test(content));
  });

  test("both lists are labelled honestly when an agent has preloaded AND on-demand attachments", () => {
    const r = compile([
      agent("Root.md", { root: true, label: "Vault" }),
      agent("Alpha.md", { label: "Alpha" }, ["Root.md"]),
      skill("Loud.md", { preload: true }, ["Alpha.md"]),
      skill("Quiet.md", {}, ["Alpha.md"]),
    ]);
    const content = fileFor(r, "agents/alpha.md");
    assert.match(frontmatterOf(content), /^skills:\n  - "vault-skills:loud"$/m);
    assert.match(content, /preloaded into your context[^\n]*`vault-skills:loud`/);
    assert.match(content, /not preloaded[^\n]*`vault-skills:quiet`/);
  });

  test("the Skill tool is still guaranteed on an explicit `tools` list when skills are attached but not preloaded", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", { tools: ["Read"] }, ["Root.md"]),
      skill("Quiet.md", {}, ["Alpha.md"]),
    ]);
    assert.match(frontmatterOf(fileFor(r, "agents/alpha.md")), /^tools: \[Read, Skill\]$/m);
  });

  test("`preload` on an agent (or `no-skills` on a skill) is a no-op and says so", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", { preload: true }, ["Root.md"]),
      skill("S.md", { "no-skills": true }, ["Alpha.md"]),
    ]);
    assert.deepEqual(r.errors, []);
    assert.deepEqual(r.warnings.sort(), [
      "Alpha.md: `preload` applies to skills — ignored on a agent note",
      "S.md: `no-skills` applies to agents — ignored on a skill note",
    ]);
    assert.ok(!/disallowedTools/.test(fileFor(r, "agents/alpha.md")));
  });

  describe("the anti-pattern guard: a cap on one agent's preload set", () => {
    const many = (n) => [
      agent("Root.md", { root: true }),
      agent("Alpha.md", {}, ["Root.md"]),
      ...Array.from({ length: n }, (_, i) => skill(`S${i}.md`, { preload: true }, ["Alpha.md"])),
    ];

    test("exceeding the default cap WARNS, naming the agent and the count — and is not an error", () => {
      const r = compile(many(DEFAULT_PRELOAD_CAP + 1));
      assert.deepEqual(r.errors, []);
      const warning = r.warnings.find((w) => /exceeds the preload cap/.test(w));
      assert.ok(warning, `expected a cap warning, got: ${JSON.stringify(r.warnings)}`);
      assert.match(warning, new RegExp(`${DEFAULT_PRELOAD_CAP + 1} skills preloaded into \`alpha\``));
      assert.match(warning, new RegExp(`cap of ${DEFAULT_PRELOAD_CAP}`));
      // The export still happens — Nelson's vault decides, the compiler only says so.
      assert.equal(r.preloads.find((p) => p.agent === "alpha").overCap, true);
      assert.match(frontmatterOf(fileFor(r, "agents/alpha.md")), /^skills:$/m);
    });

    test("at the cap exactly, nothing warns", () => {
      const r = compile(many(DEFAULT_PRELOAD_CAP));
      assert.deepEqual(r.warnings, []);
      assert.equal(r.preloads.find((p) => p.agent === "alpha").overCap, false);
    });

    test("the cap is configurable", () => {
      const strict = compile(many(3), { preloadCap: 2 });
      assert.ok(strict.warnings.some((w) => /exceeds the preload cap of 2/.test(w)));
      const loose = compile(many(3), { preloadCap: 10 });
      assert.deepEqual(loose.warnings, []);
      assert.equal(loose.preloadCap, 10);
    });

    test("the cap counts per AGENT, not per vault", () => {
      const r = compile([
        agent("Root.md", { root: true }),
        agent("Alpha.md", {}, ["Root.md"]),
        agent("Beta.md", {}, ["Root.md"]),
        ...Array.from({ length: 4 }, (_, i) => skill(`A${i}.md`, { preload: true }, ["Alpha.md"])),
        ...Array.from({ length: 4 }, (_, i) => skill(`B${i}.md`, { preload: true }, ["Beta.md"])),
      ]);
      assert.deepEqual(r.warnings, []);
    });
  });
});

// ── 4. the per-agent skill lockout ──────────────────────────────────────────

describe("no-skills: the tools-level lockout, the one real boundary", () => {
  test("emits `disallowedTools: [Skill]` and leaves an agent with no `tools` list unconstrained otherwise", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", { "no-skills": true }, ["Root.md"]),
    ]);
    const fm = frontmatterOf(fileFor(r, "agents/alpha.md"));
    assert.match(fm, /^disallowedTools: \[Skill\]$/m);
    // No `tools:` allowlist is invented — that would drop every OTHER tool too.
    assert.ok(!/^tools:/m.test(fm), `lockout must not add a tools allowlist:\n${fm}`);
  });

  test("an explicit `tools` list is preserved verbatim, and Skill is not appended for attached skills", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", { "no-skills": true, tools: ["Read", "Write"] }, ["Root.md"]),
      skill("S.md", {}, ["Alpha.md"]),
    ]);
    const fm = frontmatterOf(fileFor(r, "agents/alpha.md"));
    assert.match(fm, /^tools: \[Read, Write\]$/m);
    assert.match(fm, /^disallowedTools: \[Skill\]$/m);
  });

  test("a locked-out agent lists no skills and offers no Skills section, even with opted-in attachments", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", { "no-skills": true }, ["Root.md"]),
      skill("S.md", { preload: true }, ["Alpha.md"]),
    ]);
    const content = fileFor(r, "agents/alpha.md");
    assert.ok(!/^skills:/m.test(frontmatterOf(content)));
    assert.ok(!/## Skills/.test(content));
    assert.ok(r.warnings.some((w) => /`no-skills` is set, so the 1 skill\(s\) opted into preloading/.test(w)));
    assert.deepEqual(r.preloads, []);
  });

  test("a contradictory `tools: [Skill]` warns — the deny wins", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", { "no-skills": true, tools: ["Read", "Skill"] }, ["Root.md"]),
    ]);
    assert.ok(r.warnings.some((w) => /the deny wins; remove Skill from `tools`/.test(w)));
  });

  test("the tree records the lockout", () => {
    const r = compile([
      agent("Root.md", { root: true }),
      agent("Alpha.md", { "no-skills": true }, ["Root.md"]),
    ]);
    assert.equal(r.tree.find((n) => n.name === "alpha").noSkills, true);
    assert.equal(r.tree.find((n) => n.name === "root").noSkills, undefined);
  });
});

// ── 5. the report surfaces (validate / preview) ─────────────────────────────

/** A fake SkillsSource over in-memory notes; wikilinks resolve by basename. */
function fakeSource(notes) {
  return {
    notes: async () => notes.map((n) => ({ path: n.path, frontmatter: n.frontmatter, body: n.body })),
    resolveLink: (linkpath) => notes.find((n) => path.basename(n.path, ".md") === linkpath)?.path ?? null,
    embed: async () => null,
    basePath: () => null,
  };
}

const REPORT_VAULT = [
  { path: "Root.md", frontmatter: { type: "agent", root: true, label: "Vault" }, body: "root" },
  { path: "Alpha.md", frontmatter: { type: "agent", label: "Alpha", parent: "[[Root]]" }, body: "alpha" },
  { path: "Beta.md", frontmatter: { type: "agent", label: "Beta", parent: "[[Root]]" }, body: "beta" },
  { path: "Shared.md", frontmatter: { type: "skill", parent: ["[[Alpha]]", "[[Beta]]"], preload: true }, body: "shared" },
];

describe("validate/preview report the attachments and the preload sets", () => {
  test("analyzeVault keeps its existing shape and adds attachments / preloads / preloadCap", async () => {
    const a = await analyzeVault(fakeSource(REPORT_VAULT));
    assert.deepEqual(a.errors, []);
    assert.deepEqual(a.counts, { agents: 3, skills: 1, policies: 0, commands: 0 });
    assert.ok(Array.isArray(a.tree));
    assert.deepEqual(a.attachments, [
      { name: "shared", kind: "skill", path: "Shared.md", primary: "alpha", extra: ["beta"], preload: true },
    ]);
    assert.deepEqual(a.preloads.map((p) => p.agent).sort(), ["alpha", "beta"]);
    assert.equal(a.preloadCap, DEFAULT_PRELOAD_CAP);
  });

  test("the cap passed by the module config reaches the compile", async () => {
    const notes = [
      { path: "Root.md", frontmatter: { type: "agent", root: true }, body: "root" },
      ...Array.from({ length: 3 }, (_, i) => ({
        path: `S${i}.md`, frontmatter: { type: "skill", preload: true }, body: "s",
      })),
    ];
    const strict = await analyzeVault(fakeSource(notes), undefined, "vault-skills", 2);
    assert.ok(strict.warnings.some((w) => /exceeds the preload cap of 2/.test(w)));
    assert.equal(strict.preloadCap, 2);
    const loose = await analyzeVault(fakeSource(notes), undefined, "vault-skills", 5);
    assert.deepEqual(loose.warnings, []);
  });

  test("previewVault carries the same two reports beside its existing diff/policies shape", async () => {
    const outputDir = path.join(os.tmpdir(), "skills-transform-preview-does-not-exist");
    const p = await previewVault(fakeSource(REPORT_VAULT), { outputDir, pluginName: "vault-skills" });
    assert.ok(p.entries.length > 0);
    assert.ok(p.diff && typeof p.diff.added === "number");
    assert.deepEqual(p.policies, []);
    assert.deepEqual(p.attachments.map((x) => x.name), ["shared"]);
    assert.deepEqual(p.preloads.map((x) => x.agent).sort(), ["alpha", "beta"]);
    assert.equal(p.preloadCap, DEFAULT_PRELOAD_CAP);
  });
});

// ── 6. the authored fields honor the field-namespacing modes ────────────────

describe("`preload` / `no-skills` are read through the configured field mode", () => {
  test("prefix mode with a prefix", async () => {
    const notes = [
      { path: "Root.md", frontmatter: { "vs-type": "agent", "vs-root": true }, body: "root" },
      { path: "Locked.md", frontmatter: { "vs-type": "agent", "vs-parent": "[[Root]]", "vs-no-skills": true }, body: "locked" },
      { path: "S.md", frontmatter: { "vs-type": "skill", "vs-parent": "[[Root]]", "vs-preload": true }, body: "s" },
    ];
    const a = await analyzeVault(fakeSource(notes), { mode: "prefix", prefix: "vs-", key: "vault-skills" });
    assert.deepEqual(a.errors, []);
    assert.equal(a.tree.find((n) => n.name === "locked").noSkills, true);
    assert.equal(a.tree.find((n) => n.name === "s").preload, true);
    assert.deepEqual(a.preloads.map((p) => p.agent), ["root"]);
  });

  test("nested mode", async () => {
    const notes = [
      { path: "Root.md", frontmatter: { "vault-skills": { type: "agent", root: true } }, body: "root" },
      { path: "Locked.md", frontmatter: { "vault-skills": { type: "agent", parent: "[[Root]]", "no-skills": true } }, body: "locked" },
      { path: "S.md", frontmatter: { "vault-skills": { type: "skill", parent: "[[Root]]", preload: true } }, body: "s" },
    ];
    const a = await analyzeVault(fakeSource(notes), { mode: "nested", prefix: "", key: "vault-skills" });
    assert.deepEqual(a.errors, []);
    assert.equal(a.tree.find((n) => n.name === "locked").noSkills, true);
    assert.equal(a.tree.find((n) => n.name === "s").preload, true);
  });
});
