/**
 * skills-acceptance-stamp.test.mjs — 01.61 rule 11 (Nelson's "b" on 01.41 rule
 * 8, 2026-09-29): "The compiled artifact records each source's acceptance
 * state." Each compiled file (skill, agent, command; policies ride inside
 * agents) carries, in its generated header, one line per source: its own
 * note, every policy injected into it and every note it transcludes, each
 * with the human `verified` actor and date, and a refused embed marked NOT
 * accepted. Proven on fixtures and on REAL vault notes read from disk.
 */
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { runExport, DEFAULT_FIELDS } from "../src/kernel/exporter.ts";
import { transformAll } from "../src/kernel/transform.ts";

const F = (over) => ({ ...DEFAULT_FIELDS, typeSource: "frontmatter", ...over });
const MAP = { "Note/Skill": "skill", "Person/Agent": "agent", "Note/AgentPolicy": "policy", "Note/Command": "command" };
const human = (at) => ({ by: "human:nelson", at });

async function compile(notes, embeds, extra = {}) {
  const src = {
    notes: async () => notes,
    resolveLink: (lp) => notes.find((n) => n.path.endsWith(`/${lp}.md`))?.path ?? null,
    embed: async (lp) => {
      const hit = Object.keys(embeds).find((p) => p.endsWith(`/${lp}.md`));
      return hit ? { path: hit, content: embeds[hit] } : null;
    },
    basePath: () => null,
  };
  const outputDir = fs.mkdtempSync(path.join(os.tmpdir(), "vaultmcp-skills-stamp-"));
  try {
    const summary = await runExport(src, { outputDir, pluginName: "t", fields: F({ typeMap: MAP, includeRoots: ["In"], ...extra }) });
    const files = {};
    const walk = (d) => { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); if (e.isDirectory()) walk(p); else if (p.endsWith(".md")) files[path.relative(outputDir, p)] = fs.readFileSync(p, "utf8"); } };
    walk(outputDir);
    return { summary, files };
  } finally {
    fs.rmSync(outputDir, { recursive: true, force: true });
  }
}
const header = (content) => /<!-- generated by obsidian-vault-skills[\s\S]*?-->/.exec(content)?.[0] ?? "";

describe("01.61 rule 11 — every compiled file records each source's acceptance state", () => {
  const notes = [
    { path: "In/boss.md", frontmatter: { type: "Person/Agent", name: "boss", description: "d", verified: [human("2026-09-20T10:00:00-04:00")] }, body: "BOSS ![[fine]]" },
    { path: "In/pol.md", frontmatter: { type: "Note/AgentPolicy", name: "pol", parent: "[[boss]]", verified: [human("2026-09-21T11:00:00-04:00")] }, body: "POLICY-TEXT" },
    { path: "In/sk.md", frontmatter: { type: "Note/Skill", name: "sk", verified: [human("2026-09-22T12:00:00-04:00"), { by: "vault-mcp/0.19.0", at: "2026-09-28T00:00:00Z" }] }, body: "SK ![[fine]] ![[secret]]" },
    { path: "In/cmd.md", frontmatter: { type: "Note/Command", description: "c", verified: [human("2026-09-23T13:00:00-04:00")] }, body: "CMD $ARGUMENTS" },
  ];
  const embeds = {
    "In/fine.md": "---\ntype: Note\nverified:\n  - by: human:nelson\n    at: 2026-09-24T14:00:00-04:00\n---\nFINE-TEXT",
    "In/secret.md": "---\ntype: Note\n---\nSECRET-TEXT",
  };

  test("a skill names its own note, each embed it inlined with the embed's verification, and each refused embed as NOT accepted", async () => {
    const { files } = await compile(notes, embeds);
    const h = header(files["skills/sk/SKILL.md"]);
    assert.match(h, /acceptance \(01\.61 rule 11\):/);
    assert.match(h, /In\/sk\.md — verified by human:nelson at 2026-09-22T12:00:00-04:00\n/, "its own note; the LAST human entry, not the later machine one");
    assert.match(h, /In\/fine\.md \(transcluded\) — verified by human:nelson at 2026-09-24T14:00:00-04:00/);
    assert.match(h, /In\/secret\.md \(transcluded\) — NOT accepted; its text was not inlined/);
    assert.doesNotMatch(h, /vault-mcp\/0\.19\.0/, "a machine entry is not an acceptance");
  });

  test("an agent names its own note, the policy injected into it, and the notes transcluded into it", async () => {
    const { files } = await compile(notes, embeds);
    const h = header(files["agents/boss.md"]);
    assert.match(h, /In\/boss\.md — verified by human:nelson at 2026-09-20T10:00:00-04:00/);
    assert.match(h, /In\/pol\.md \(policy\) — verified by human:nelson at 2026-09-21T11:00:00-04:00/);
    assert.match(h, /In\/fine\.md \(transcluded\) — verified by human:nelson at 2026-09-24T14:00:00-04:00/);
    assert.ok(files["agents/boss.md"].includes("POLICY-TEXT"), "the policy did land in the agent");
  });

  test("a command names its own note", async () => {
    const { files } = await compile(notes, embeds);
    assert.match(header(files["commands/cmd.md"]), /In\/cmd\.md — verified by human:nelson at 2026-09-23T13:00:00-04:00/);
  });

  test("EVERY compiled file carries the block; the synthesized root says it has no source note", async () => {
    const { files } = await compile(notes, embeds);
    const compiled = Object.entries(files).filter(([, c]) => c.includes("generated by obsidian-vault-skills"));
    assert.ok(compiled.length >= 4, Object.keys(files).join(", "));
    for (const [rel, c] of compiled) assert.match(header(c), /acceptance \(01\.61 rule 11\):\n {7}\S/, `${rel} records acceptance`);
    const root = compiled.find(([, c]) => c.includes("(synthesized root)"));
    assert.ok(root, "the synthesized root is emitted");
    assert.match(header(root[1]), /\(synthesized root\) — generated by the compiler; no source note/);
  });

  test("a date parsed as a YAML timestamp (Obsidian's cache hands a Date) is recorded as ISO; an entry with no date records the actor alone", async () => {
    const n2 = [
      { path: "In/d.md", frontmatter: { type: "Note/Skill", name: "d", verified: [{ by: "human:nelson", at: new Date("2026-09-25T09:08:39Z") }] }, body: "D" },
      { path: "In/e.md", frontmatter: { type: "Note/Skill", name: "e", verified: [{ by: "human:nelson" }] }, body: "E" },
    ];
    const { files } = await compile(n2, {});
    assert.match(header(files["skills/d/SKILL.md"]), /In\/d\.md — verified by human:nelson at 2026-09-25T09:08:39\.000Z/);
    assert.match(header(files["skills/e/SKILL.md"]), /In\/e\.md — verified by human:nelson -->$/);
  });

  test("a path, actor or date carrying '-->' or '--!>' cannot close the header comment early", async () => {
    const n4 = [{ path: "In/x.md", frontmatter: { type: "Note/Skill", name: "x", verified: [{ by: "human:a-->b", at: "2026--!>09" }] }, body: "X" }];
    const c4 = (await compile(n4, {})).files["skills/x/SKILL.md"];
    assert.equal((c4.match(/--!?>/g) ?? []).length, 1, "one terminator: the actor and date are softened");
    assert.match(header(c4), /verified by human:a--›b at 2026--!›09/);
    const n3 = [{ path: "In/a --> b.md", frontmatter: { type: "Note/Skill", name: "ab", verified: [human("2026-09-26")] }, body: "AB" }];
    const { files } = await compile(n3, {});
    const c = files["skills/ab/SKILL.md"];
    assert.equal((c.match(/-->/g) ?? []).length, 1, "exactly one comment terminator in the whole file");
    assert.match(header(c), /In\/a --› b\.md — verified by human:nelson at 2026-09-26/);
    assert.match(header(c), /from vault note: In\/a --› b\.md\n/, "the header's source line is softened too (it was not, before this PR)");
  });
});

describe("01.61 rule 11 — the edges the first cut left untested", () => {
  const H = (at) => [human(at)];
  test("a transclusion marker softens '--!>' like the header does", async () => {
    const notes = [{ path: "In/h.md", frontmatter: { type: "Note/Skill", name: "h", verified: H("2026-09-01") }, body: "H ![[a --!> b]]" }];
    const embeds = { "In/a --!> b.md": "---\nverified:\n  - by: human:nelson\n    at: 2026-09-02\n---\nINNER" };
    const c = (await compile(notes, embeds)).files["skills/h/SKILL.md"];
    assert.ok(c.includes("INNER"), "the accepted embed inlined");
    assert.ok(!c.includes("--!>"), "no raw --!> anywhere in the compiled file");
  });

  test("a cross-cutting agent records the hard policies inlined from other scopes, and a policy's marker is softened", async () => {
    const notes = [
      { path: "In/scope.md", frontmatter: { type: "Person/Agent", name: "scope", description: "s", verified: H("2026-09-01") }, body: "SCOPE" },
      { path: "In/hard --> p.md", frontmatter: { type: "Note/AgentPolicy", name: "hp", parent: "[[scope]]", severity: "hard", verified: H("2026-09-02") }, body: "HARD-POLICY-TEXT ![[pe]]" },
      { path: "In/xc.md", frontmatter: { type: "Person/Agent", name: "xc", description: "x", crosscutting: true, verified: H("2026-09-03") }, body: "XC" },
    ];
    const embeds = { "In/pe.md": "---\nverified:\n  - by: human:nelson\n    at: 2026-09-04\n---\nPOLICY-EMBED-TEXT" };
    const { files } = await compile(notes, embeds);
    const xc = files["agents/xc.md"];
    assert.ok(xc.includes("HARD-POLICY-TEXT"), "the hard policy was inlined into the cross-cutting agent");
    assert.match(header(xc), /In\/hard --› p\.md \(policy\) — verified by human:nelson at 2026-09-02/, "the hard-inline policy is recorded");
    assert.match(header(xc), /In\/pe\.md \(transcluded\) — verified by human:nelson at 2026-09-04/, "an embed inside a policy body is recorded in the agent");
    assert.ok(xc.includes("<!-- policy: In/hard --› p.md -->"), "the policy marker is softened");
    for (const m of xc.matchAll(/<!--([\s\S]*?)-->/g)) assert.ok(!/policy: In\/hard $|from vault note: In\/hard $/.test(m[1]), `a comment closed early: ${m[0]}`);
  });

  test("an agent records a refused embed as NOT accepted; a command records its embeds; lines are sorted within each role", async () => {
    const notes = [
      { path: "In/boss.md", frontmatter: { type: "Person/Agent", name: "boss", description: "d", verified: [human("2026-09-20")] }, body: "B ![[zz]] ![[aa]] ![[no]]" },
      { path: "In/cmd.md", frontmatter: { type: "Note/Command", description: "c", verified: [human("2026-09-23")] }, body: "C ![[aa]] ![[no]]" },
    ];
    const ok = "---\nverified:\n  - by: human:nelson\n    at: 2026-09-05\n---\nOK";
    const embeds = { "In/aa.md": ok, "In/zz.md": ok, "In/no.md": "---\ntype: Note\n---\nNO-TEXT" };
    const { files } = await compile(notes, embeds);
    const hb = header(files["agents/boss.md"]);
    assert.match(hb, /In\/no\.md \(transcluded\) — NOT accepted; its text was not inlined/);
    const [ia, ino, iz] = ["In/aa.md (transcluded)", "In/no.md (transcluded)", "In/zz.md (transcluded)"].map((l) => hb.indexOf(l));
    assert.ok(ia >= 0 && ino >= 0 && iz >= 0, "all three lines are present");
    assert.ok(ia < ino && ino < iz, "sorted by path");
    const hc = header(files["commands/cmd.md"]);
    assert.match(hc, /In\/aa\.md \(transcluded\) — verified by human:nelson at 2026-09-05/);
    assert.match(hc, /In\/no\.md \(transcluded\) — NOT accepted/);
  });

  test("a REFUSED embed reads NOT accepted even if the map holds a record for it (the two gates disagreeing cannot make a line claim what was not inlined)", () => {
    const out = transformAll(
      [{ path: "In/s.md", frontmatter: { type: "skill", name: "s" }, body: "S", parentPaths: [], sources: ["In/e.md"] }],
      { pluginName: "t", acceptance: new Map([["In/s.md", { by: "human:n", at: "1" }], ["In/e.md", { by: "human:n", at: "2" }]]), refused: new Set(["In/e.md"]) },
    );
    const c = out.generated.find((g) => g.relOut === "skills/s/SKILL.md").content;
    assert.match(header(c), /In\/e\.md \(transcluded\) — NOT accepted/);
  });
});

// ── on REAL vault notes, read from disk ────────────────────────────────────────
// The notes are CHOSEN at run time from a real spec folder: one that carries a
// human verified entry, and one that carries no `verified` key at all. Pinning
// two named notes would turn red the day Nelson verifies the second one.
const VAULT = process.env.VAULT_MCP_LIVE_VAULT ?? path.join(os.homedir(), "obsidian");
const REAL_DIR = path.join(VAULT, "00-09 System/01 System architecture");
const fmBlock = (t) => /^---\n([\s\S]*?)\n---\n/.exec(t)?.[1] ?? null;
/** The LAST `by: human:…` entry's actor and date, by a plain line scan (not the parser under test). */
function lastHuman(fm) {
  const lines = fm.split("\n"); const start = lines.findIndex((l) => /^verified:\s*$/.test(l));
  if (start < 0) return null;
  let found = null, cur = null;
  for (const l of lines.slice(start + 1)) {
    if (/^\S/.test(l)) break;
    const by = /^\s*-\s+by:\s*["']?(human:[^"'\s]+)["']?\s*$/.exec(l);
    if (/^\s*-\s/.test(l)) cur = null;
    if (by) { cur = { by: by[1], at: null }; found = cur; continue; }
    const at = /^\s+at:\s*["']?([^"']+?)["']?\s*$/.exec(l);
    if (at && cur) cur.at = at[1];
  }
  return found;
}
function pickReal() {
  if (!fs.existsSync(REAL_DIR)) return null;
  const files = [];
  const walk = (d) => { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); if (e.isDirectory()) walk(p); else if (p.endsWith(".md")) files.push(p); } };
  walk(REAL_DIR);
  files.sort();
  let acc = null, una = null;
  for (const f of files) {
    const t = fs.readFileSync(f, "utf8"); const fm = fmBlock(t); if (fm === null) continue;
    if (!acc && lastHuman(fm)?.at) acc = { f, t, rec: lastHuman(fm) };
    const body = t.slice(t.indexOf("\n---\n") + 5).split("\n").find((l) => l.trim().length > 30);
    if (!una && !/^verified:/m.test(fm) && body) una = { f, t, body: body.trim() };
    if (acc && una) break;
  }
  return acc && una ? { acc, una } : null;
}
const REAL = pickReal();

describe("01.61 rule 11 on real vault notes (skipped where the vault is absent)", { skip: REAL ? false : `no usable notes under ${REAL_DIR}` }, () => {
  test("a real verified note embedded in a compiled skill is recorded with the actor and date its file carries; a real unverified note is recorded as NOT accepted and none of its text ships", async () => {
    const A = path.basename(REAL.acc.f, ".md"), U = path.basename(REAL.una.f, ".md");
    const embeds = { [`In/${A}.md`]: REAL.acc.t, [`In/${U}.md`]: REAL.una.t };
    const notes = [{ path: "In/host.md", frontmatter: { type: "Note/Skill", name: "host", verified: [human("2026-09-29")] }, body: `HOST ![[${A}]] ![[${U}]]` }];
    const { files } = await compile(notes, embeds);
    const c = files["skills/host/SKILL.md"];
    const h = header(c);
    const want = `In/${A}.md (transcluded) — verified by ${REAL.acc.rec.by} at ${REAL.acc.rec.at}`;
    assert.ok(h.includes(want + "\n") || h.includes(want + " -->"), `the whole line, not a prefix of it — ${REAL.acc.f}\n${h}`);
    assert.ok(h.includes(`In/${U}.md (transcluded) — NOT accepted; its text was not inlined`), h);
    assert.ok(!c.includes(REAL.una.body), "no text of the unaccepted real note reaches the artifact");
  });
});
