/**
 * skills-acceptance-stamp.test.mjs — 01.61 rule 11 (Nelson's "b" on 01.41 rule
 * 8, 2026-09-29): "The compiled artifact records each source's acceptance
 * state." Each compiled file (skill, agent, command; policies ride inside
 * agents) carries, in its generated header, one line per source: its own
 * note, every policy injected into it and every note it transcludes, each
 * with the human `verified` actor and date, and a refused embed marked NOT
 * accepted. Proven on fixtures and on REAL vault notes read from disk.
 */
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { runExport, DEFAULT_FIELDS } from "../src/kernel/exporter.ts";

const F = (over) => ({ ...DEFAULT_FIELDS, typeSource: "frontmatter", ...over });
const MAP = { "Note/Skill": "skill", "Person/Agent": "agent", "Note/AgentPolicy": "policy", "Note/Command": "command" };
const human = (at) => ({ by: "human:nelson", at });

async function compile(notes, embeds, extra = {}) {
  const src = {
    notes: async () => notes,
    resolveLink: (lp) => notes.find((n) => n.path.endsWith(`/${lp}.md`))?.path ?? null,
    embed: async (lp) => {
      const hit = Object.keys(embeds).find((p) => p.endsWith(`/${lp}.md`));
      return hit ? { path: hit, content: embeds[hit] } : null;
    },
    basePath: () => null,
  };
  const outputDir = fs.mkdtempSync(path.join(os.tmpdir(), "vaultmcp-skills-stamp-"));
  try {
    const summary = await runExport(src, { outputDir, pluginName: "t", fields: F({ typeMap: MAP, includeRoots: ["In"], ...extra }) });
    const files = {};
    const walk = (d) => { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); if (e.isDirectory()) walk(p); else if (p.endsWith(".md")) files[path.relative(outputDir, p)] = fs.readFileSync(p, "utf8"); } };
    walk(outputDir);
    return { summary, files };
  } finally {
    fs.rmSync(outputDir, { recursive: true, force: true });
  }
}
const header = (content) => /<!-- generated by obsidian-vault-skills[\s\S]*?-->/.exec(content)?.[0] ?? "";

describe("01.61 rule 11 — every compiled file records each source's acceptance state", () => {
  const notes = [
    { path: "In/boss.md", frontmatter: { type: "Person/Agent", name: "boss", description: "d", verified: [human("2026-09-20T10:00:00-04:00")] }, body: "BOSS ![[fine]]" },
    { path: "In/pol.md", frontmatter: { type: "Note/AgentPolicy", name: "pol", parent: "[[boss]]", verified: [human("2026-09-21T11:00:00-04:00")] }, body: "POLICY-TEXT" },
    { path: "In/sk.md", frontmatter: { type: "Note/Skill", name: "sk", verified: [human("2026-09-22T12:00:00-04:00"), { by: "vault-mcp/0.19.0", at: "2026-09-28T00:00:00Z" }] }, body: "SK ![[fine]] ![[secret]]" },
    { path: "In/cmd.md", frontmatter: { type: "Note/Command", description: "c", verified: [human("2026-09-23T13:00:00-04:00")] }, body: "CMD $ARGUMENTS" },
  ];
  const embeds = {
    "In/fine.md": "---\ntype: Note\nverified:\n  - by: human:nelson\n    at: 2026-09-24T14:00:00-04:00\n---\nFINE-TEXT",
    "In/secret.md": "---\ntype: Note\n---\nSECRET-TEXT",
  };

  test("a skill names its own note, each embed it inlined with the embed's verification, and each refused embed as NOT accepted", async () => {
    const { files } = await compile(notes, embeds);
    const h = header(files["skills/sk/SKILL.md"]);
    assert.match(h, /acceptance \(01\.61 rule 11\):/);
    assert.match(h, /In\/sk\.md — verified by human:nelson at 2026-09-22T12:00:00-04:00\n/, "its own note; the LAST human entry, not the later machine one");
    assert.match(h, /In\/fine\.md \(transcluded\) — verified by human:nelson at 2026-09-24T14:00:00-04:00/);
    assert.match(h, /In\/secret\.md \(transcluded\) — NOT accepted; its text was not inlined/);
    assert.doesNotMatch(h, /vault-mcp\/0\.19\.0/, "a machine entry is not an acceptance");
  });

  test("an agent names its own note, the policy injected into it, and the notes transcluded into it", async () => {
    const { files } = await compile(notes, embeds);
    const h = header(files["agents/boss.md"]);
    assert.match(h, /In\/boss\.md — verified by human:nelson at 2026-09-20T10:00:00-04:00/);
    assert.match(h, /In\/pol\.md \(policy\) — verified by human:nelson at 2026-09-21T11:00:00-04:00/);
    assert.match(h, /In\/fine\.md \(transcluded\) — verified by human:nelson at 2026-09-24T14:00:00-04:00/);
    assert.ok(files["agents/boss.md"].includes("POLICY-TEXT"), "the policy did land in the agent");
  });

  test("a command names its own note", async () => {
    const { files } = await compile(notes, embeds);
    assert.match(header(files["commands/cmd.md"]), /In\/cmd\.md — verified by human:nelson at 2026-09-23T13:00:00-04:00/);
  });

  test("EVERY compiled file carries the block; the synthesized root says it has no source note", async () => {
    const { files } = await compile(notes, embeds);
    const compiled = Object.entries(files).filter(([, c]) => c.includes("generated by obsidian-vault-skills"));
    assert.ok(compiled.length >= 4, Object.keys(files).join(", "));
    for (const [rel, c] of compiled) assert.match(header(c), /acceptance \(01\.61 rule 11\):\n {7}\S/, `${rel} records acceptance`);
    const root = compiled.find(([, c]) => c.includes("(synthesized root)"));
    if (root) assert.match(header(root[1]), /\(synthesized root\) — generated by the compiler; no source note/);
  });

  test("a date parsed as a YAML timestamp (Obsidian's cache hands a Date) is recorded as ISO; an entry with no date records the actor alone", async () => {
    const n2 = [
      { path: "In/d.md", frontmatter: { type: "Note/Skill", name: "d", verified: [{ by: "human:nelson", at: new Date("2026-09-25T09:08:39Z") }] }, body: "D" },
      { path: "In/e.md", frontmatter: { type: "Note/Skill", name: "e", verified: [{ by: "human:nelson" }] }, body: "E" },
    ];
    const { files } = await compile(n2, {});
    assert.match(header(files["skills/d/SKILL.md"]), /In\/d\.md — verified by human:nelson at 2026-09-25T09:08:39\.000Z/);
    assert.match(header(files["skills/e/SKILL.md"]), /In\/e\.md — verified by human:nelson -->$/);
  });

  test("a path or actor carrying '-->' cannot close the header comment early", async () => {
    const n3 = [{ path: "In/a --> b.md", frontmatter: { type: "Note/Skill", name: "ab", verified: [human("2026-09-26")] }, body: "AB" }];
    const { files } = await compile(n3, {});
    const c = files["skills/ab/SKILL.md"];
    assert.equal((c.match(/-->/g) ?? []).length, 1, "exactly one comment terminator in the whole file");
    assert.match(header(c), /In\/a --› b\.md — verified by human:nelson at 2026-09-26/);
    assert.match(header(c), /from vault note: In\/a --› b\.md\n/, "the header's source line is softened too (it was not, before this PR)");
  });
});

// ── on REAL vault notes, read from disk ────────────────────────────────────────
const VAULT = process.env.VAULT_MCP_LIVE_VAULT ?? path.join(os.homedir(), "obsidian");
const REAL_DIR = "00-09 System/01 System architecture/01.25 Bands";
const REAL_ACCEPTED = `${REAL_DIR}/Does a band inherit allowedTags.md`;
const REAL_UNACCEPTED = `${REAL_DIR}/Does a band note join the up prev and next chains.md`;
const haveVault = fs.existsSync(path.join(VAULT, REAL_ACCEPTED)) && fs.existsSync(path.join(VAULT, REAL_UNACCEPTED));

describe("01.61 rule 11 on real vault notes (skipped where the vault is absent)", { skip: haveVault ? false : `no vault at ${VAULT}` }, () => {
  test("a real verified note embedded in a compiled skill is recorded with the actor and date its file carries; a real unverified note is recorded as NOT accepted and none of its text ships", async () => {
    const acc = fs.readFileSync(path.join(VAULT, REAL_ACCEPTED), "utf8");
    const una = fs.readFileSync(path.join(VAULT, REAL_UNACCEPTED), "utf8");
    // The expected record, read from the file by a plain scan — not by the parser under test.
    const m = /^verified:\n(?:.*\n)*?\s*- by: (human:\S+)\n\s+at: (\S+)/m.exec(acc);
    assert.ok(m, "the real accepted note carries a human verified entry");
    assert.doesNotMatch(una, /^verified:\n\s*- by: human:/m, "the real unaccepted note carries none");
    const unaBody = una.replace(/^---\n[\s\S]*?\n---\n/, "").split("\n").find((l) => l.trim().length > 30) ?? "";
    assert.ok(unaBody.length > 30, "a distinctive line from the unaccepted note's body");
    const embeds = { [`In/${path.basename(REAL_ACCEPTED)}`]: acc, [`In/${path.basename(REAL_UNACCEPTED)}`]: una };
    const notes = [{ path: "In/host.md", frontmatter: { type: "Note/Skill", name: "host", verified: [human("2026-09-29")] },
      body: `HOST ![[${path.basename(REAL_ACCEPTED, ".md")}]] ![[${path.basename(REAL_UNACCEPTED, ".md")}]]` }];
    const { files } = await compile(notes, embeds);
    const c = files["skills/host/SKILL.md"];
    const h = header(c);
    assert.ok(h.includes(`In/${path.basename(REAL_ACCEPTED)} (transcluded) — verified by ${m[1]} at ${m[2]}`), h);
    assert.ok(h.includes(`In/${path.basename(REAL_UNACCEPTED)} (transcluded) — NOT accepted; its text was not inlined`), h);
    assert.ok(!c.includes(unaBody.trim()), "no text of the unaccepted real note reaches the artifact");
  });
});
