// Ported from obsidian-jd-dashboard's src/lib/category-index.ts: rebuilds the
// `## Contents` section of `XX.00` JDex index files at three tiers, walking
// VAULT FILES (not a jd-index.yaml registry — see this fold's design doc for
// why that data model is dropped) —
//
//   1. Ordinary per-category    — `XX.00` where XX ∉ {00, 10, 20, … 90}.
//      Lists the category's own folder members.
//   2. Area-management          — `X0.00` where X ∈ {1..9}.
//      Consolidates every per-category `## Contents` within the same area.
//   3. System                   — `00.00`.
//      Consolidates every per-category `## Contents` across all areas.
//
// Descriptions following an em-dash-alternative `*(…)*` annotation are
// preserved at every tier — the parent tier's local description wins over an
// inherited one.
//
// Every TFile-shaped function in the original (getCategoryFiles,
// buildCategoriesMap, formatBullet, buildLinks, bulletsForCategory) is
// ported over PLAIN VAULT-RELATIVE PATH STRINGS instead — this file imports
// nothing from `obsidian` (kernel-module rule). The two functions that read
// OTHER files' content in the original (`app.vault.read` inside
// bulletsForCategory, called per sibling category at the area/system tiers)
// take that content pre-fetched instead, via `siblingContent: Map<path,
// content>` — the glue layer (mcp/tools-jd-scaffold.ts) does the actual
// vault I/O and hands this module an already-resolved snapshot.

import { setSection } from "./sections.js";

export interface PreservedDescription {
  file: string;
  target: string;
  description: string;
}

export interface ReindexPlan {
  newContent: string;
  preserved: PreservedDescription[];
}

export interface PlanReindexInput {
  /** The `XX.00` file being reindexed. */
  targetIndexPath: string;
  /** Every markdown file's vault path — the listing planning reads from. */
  allPaths: string[];
  /** Every category `XX.00` file's CURRENT raw content, keyed by path —
   *  must include `targetIndexPath` itself. Used directly at the ordinary
   *  tier (just the target); used to read SIBLING categories' `##
   *  Contents` at the area/system tiers (bulletsForCategory's cross-read in
   *  the original). A path with no entry is treated as an empty file. */
  siblingContent: Map<string, string>;
}

/** Single warning callout used at every tier — bullets regenerate from the
 *  vault on each run, italic-paren descriptions persist across runs. `*(…)*`
 *  rather than an em-dash separator: obsidian-linter's
 *  `remove-space-around-characters`/`remove-link-spacing` rules (with
 *  `include-dashes: true`) mangle `[[link]] — desc` into shapes the parser
 *  below can't reliably recover (ported verbatim from jd-dashboard). */
export const CONTENTS_CALLOUT =
  `> [!warning]+ Auto-generated—descriptions preserved\n` +
  `> Regenerated by \`obsidian_jd_reindex_category\`. Bullet links rebuild from the vault on each run; italic-paren descriptions after each link (\`[[…]] *(note)*\`) are preserved.`;

/** Match a bullet line `- [[target(|alias)?]] *(desc)*?`. */
const BULLET_RE = /^-\s+\[\[([^\]|]+)(?:\|([^\]]*))?\]\](?:\s+\*\((.+)\)\*)?$/;

/** True for `10`, `20`, … `90` — the area-management JDex prefixes. */
export function isAreaManagement(prefix: string): boolean {
  return prefix.length === 2 && prefix !== "00" && prefix.endsWith("0");
}

/** basename with the `.md` extension stripped — the original's `TFile.basename`. */
function basenameOf(path: string): string {
  const idx = path.lastIndexOf("/");
  const name = idx === -1 ? path : path.slice(idx + 1);
  return name.endsWith(".md") ? name.slice(0, -3) : name;
}

/** Parent folder's vault path — "" for a root-level file. */
function folderOf(path: string): string {
  const idx = path.lastIndexOf("/");
  return idx === -1 ? "" : path.slice(0, idx);
}

/** The last path segment of a folder path (its own "name") — "" for the vault root. */
function nameOf(folderPath: string): string {
  const idx = folderPath.lastIndexOf("/");
  return idx === -1 ? folderPath : folderPath.slice(idx + 1);
}

/** Format a single bullet from a basename, applying an optional description. */
function formatBullet(basename: string, description?: string): string {
  const subMatch = basename.match(/^(\d{5,})\.00\s+(.+)$/);
  const link = subMatch ? `[[${basename}|${subMatch[1]} ${subMatch[2]}]]` : `[[${basename}]]`;
  return description ? `- ${link} *(${description})*` : `- ${link}`;
}

export function buildLinks(basenames: string[]): string {
  return basenames.map((bn) => formatBullet(bn)).join("\n");
}

/**
 * Category-member paths, EXCLUDING the index file itself. Path matching is
 * separator-bounded — a category at `"06 Foo"` doesn't scoop files from a
 * sibling `"06 Foo Long"`.
 */
export function getCategoryFiles(allPaths: string[], prefix: string, folderPath: string, excludePath?: string): string[] {
  return allPaths
    .filter((p) => {
      if (excludePath && p === excludePath) return false;
      if (!basenameOf(p).startsWith(prefix)) return false;
      const parent = folderOf(p);
      if (parent !== folderPath && !parent.startsWith(folderPath + "/")) return false;
      return true;
    })
    .sort((a, b) => basenameOf(a).localeCompare(basenameOf(b)));
}

/** Parse every bullet line in `content`, returning a `target -> description`
 *  map for those carrying an italic-paren annotation. Whole-file, not
 *  section-scoped, so an annotation the user wrote in their own sections
 *  (e.g. `## IDs`) migrates into `## Contents` on the next reindex. */
export function parseAllDescriptions(content: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const line of content.split("\n")) {
    const m = line.trim().match(BULLET_RE);
    if (!m) continue;
    const [, target, , desc] = m;
    if (desc) out.set(target, desc);
  }
  return out;
}

/** Apply an overlay description map onto a block of bullet lines — an
 *  overlay entry trumps any pre-existing description on that bullet. */
export function overlayDescriptions(bullets: string, overlay: Map<string, string>): { text: string; applied: Array<[string, string]> } {
  const applied: Array<[string, string]> = [];
  const out = bullets.split("\n").map((line) => {
    const m = line.trim().match(BULLET_RE);
    if (!m) return line;
    const [, target, alias] = m;
    const desc = overlay.get(target);
    if (!desc) return line;
    applied.push([target, desc]);
    const link = alias ? `[[${target}|${alias}]]` : `[[${target}]]`;
    return `- ${link} *(${desc})*`;
  });
  return { text: out.join("\n"), applied };
}

/** Pull just the bullet lines (verbatim) from a `## Contents` section. */
export function extractContentsBullets(content: string): string {
  const lines = content.split("\n");
  const start = lines.findIndex((l) => l.trim() === "## Contents");
  if (start === -1) return "";
  const out: string[] = [];
  for (let i = start + 1; i < lines.length; i++) {
    const t = lines[i].trim();
    if (/^## [^#]/.test(t) || t === "^contents") break;
    if (t.startsWith("- [[")) out.push(lines[i]);
  }
  return out.join("\n");
}

/** Render the `## Contents` body for an ordinary per-category `XX.00`.
 *  Bullets are sorted by basename so preserved descriptions never affect order. */
export function buildContents(basenames: string[], descriptions: Map<string, string>): string {
  const sorted = [...basenames].sort((a, b) => a.localeCompare(b));
  const bullets = sorted.map((bn) => formatBullet(bn, descriptions.get(bn))).join("\n");
  return `${CONTENTS_CALLOUT}\n\n${bullets}`;
}

interface CategoryData {
  prefix: string;
  indexPath: string;
  indexBasename: string;
  folderPath: string;
  folderName: string;
  /** The category folder's parent folder's name — "" for a category folder
   *  that sits directly at the vault root (no area above it), matching
   *  Obsidian's own root TFolder.name convention. This is an edge case a
   *  well-formed JD vault shouldn't hit in practice (every real category is
   *  nested area/category, two levels deep) — kept as a plain string rather
   *  than modeling it as null/undefined, since the original's own
   *  `areaFolder?.name` optional-chain never actually resolves to
   *  null/undefined for a real file either (Obsidian's TFolder.parent chain
   *  always terminates at the root folder, never at null). */
  areaFolderName: string;
  memberBasenames: string[];
}

/** Build the prefix -> CategoryData map, discovering categories by `XX.00`
 *  filename (next char space/dot/plus), matching ensureCategoryIndexes'
 *  acceptance rule. First-write-wins on a duplicate prefix. */
function buildCategoriesMap(allPaths: string[]): Map<string, CategoryData> {
  const indexPaths = allPaths.filter((p) => /^\d{2}\.00(?:\s|\.|\+|$)/.test(basenameOf(p)));
  const out = new Map<string, CategoryData>();
  for (const indexPath of indexPaths) {
    const m = basenameOf(indexPath).match(/^(\d{2})/);
    if (!m) continue;
    const prefix = m[1];
    if (out.has(prefix)) continue;
    const folderPath = folderOf(indexPath);
    out.set(prefix, {
      prefix,
      indexPath,
      indexBasename: basenameOf(indexPath),
      folderPath,
      folderName: nameOf(folderPath),
      areaFolderName: nameOf(folderOf(folderPath)),
      memberBasenames: getCategoryFiles(allPaths, prefix, folderPath, indexPath).map(basenameOf),
    });
  }
  return out;
}

/** Bullets for one category's contribution to a consolidated view. For the
 *  consolidating file's own category, rebuild fresh from the vault. For
 *  siblings, copy their `## Contents` verbatim from `siblingContent`
 *  (falling back to a fresh build if empty/missing), prepending the
 *  sibling's own `XX.00` link so that index file isn't an orphan. */
function bulletsForCategory(cat: CategoryData, selfIndexPath: string, siblingContent: Map<string, string>): string {
  if (cat.indexPath === selfIndexPath) return buildLinks(cat.memberBasenames);
  const content = siblingContent.get(cat.indexPath) ?? "";
  const inner = extractContentsBullets(content) || buildLinks(cat.memberBasenames);
  const indexBullet = `- [[${cat.indexBasename}]]`;
  return inner ? `${indexBullet}\n${inner}` : indexBullet;
}

function reindexOrdinary(targetIndexPath: string, allPaths: string[], currentContent: string): ReindexPlan {
  const prefix = basenameOf(targetIndexPath).match(/^(\d{2})/)![1];
  const folderPath = folderOf(targetIndexPath);
  const catBasenames = getCategoryFiles(allPaths, prefix, folderPath, targetIndexPath).map(basenameOf);

  const descriptions = parseAllDescriptions(currentContent);
  const body = buildContents(catBasenames, descriptions);
  const newContent = setSection(currentContent, "## Contents", body);

  const catSet = new Set(catBasenames);
  const preserved: PreservedDescription[] = [];
  for (const [target, description] of descriptions) {
    if (catSet.has(target)) preserved.push({ file: targetIndexPath, target, description });
  }
  return { newContent, preserved };
}

function reindexAreaManagement(targetIndexPath: string, categories: Map<string, CategoryData>, currentContent: string, siblingContent: Map<string, string>): ReindexPlan {
  const selfPrefix = basenameOf(targetIndexPath).match(/^(\d{2})/)![1];
  const self = categories.get(selfPrefix);
  if (!self) return { newContent: currentContent, preserved: [] };
  const areaName = self.areaFolderName;

  const areaCats = [...categories.values()].filter((c) => c.areaFolderName === areaName).sort((a, b) => a.prefix.localeCompare(b.prefix));

  const overlay = parseAllDescriptions(currentContent);
  const preserved: PreservedDescription[] = [];
  let body = `${CONTENTS_CALLOUT}\n\n`;
  for (const cat of areaCats) {
    body += `### ${cat.folderName}\n\n`;
    const bullets = bulletsForCategory(cat, targetIndexPath, siblingContent);
    const result = overlayDescriptions(bullets, overlay);
    for (const [target, description] of result.applied) preserved.push({ file: targetIndexPath, target, description });
    body += result.text + "\n\n";
  }

  const newContent = setSection(currentContent, "## Contents", body);
  return { newContent, preserved };
}

function reindexSystem(targetIndexPath: string, categories: Map<string, CategoryData>, currentContent: string, siblingContent: Map<string, string>): ReindexPlan {
  const areas = new Map<string, CategoryData[]>();
  for (const cat of categories.values()) {
    const areaName = cat.areaFolderName || "(no area)";
    if (!areas.has(areaName)) areas.set(areaName, []);
    areas.get(areaName)!.push(cat);
  }
  const sortedAreas = [...areas.entries()].sort((a, b) => a[0].localeCompare(b[0]));

  const overlay = parseAllDescriptions(currentContent);
  const preserved: PreservedDescription[] = [];
  let body = `${CONTENTS_CALLOUT}\n\n`;
  for (const [areaName, areaCats] of sortedAreas) {
    body += `### ${areaName}\n\n`;
    areaCats.sort((a, b) => a.prefix.localeCompare(b.prefix));
    for (const cat of areaCats) {
      body += `#### ${cat.folderName}\n\n`;
      const bullets = bulletsForCategory(cat, targetIndexPath, siblingContent);
      const result = overlayDescriptions(bullets, overlay);
      for (const [target, description] of result.applied) preserved.push({ file: targetIndexPath, target, description });
      body += result.text + "\n\n";
    }
  }

  const newContent = setSection(currentContent, "## Contents", body);
  return { newContent, preserved };
}

/**
 * Single dispatch entry point. Routes by prefix: `00` -> system
 * consolidation, `10`…`90` -> area-management consolidation, everything
 * else -> ordinary per-category list. Returns `null` only when
 * `targetIndexPath` isn't `XX.00`-shaped at all — a root-level `XX.00` file
 * (no containing area folder) is still processed normally, with an empty
 * folder name, matching the original's real behavior (Obsidian's own
 * TFolder.parent chain always terminates at the root folder, never at
 * null/undefined, so the original's defensive `!indexFile.parent` check
 * never actually fires for a real file).
 */
export function planReindexCategory(input: PlanReindexInput): ReindexPlan | null {
  const { targetIndexPath, allPaths, siblingContent } = input;
  const prefixMatch = basenameOf(targetIndexPath).match(/^(\d{2})/);
  if (!prefixMatch) return null;
  const prefix = prefixMatch[1];
  const currentContent = siblingContent.get(targetIndexPath) ?? "";

  if (prefix === "00") return reindexSystem(targetIndexPath, buildCategoriesMap(allPaths), currentContent, siblingContent);
  if (isAreaManagement(prefix)) return reindexAreaManagement(targetIndexPath, buildCategoriesMap(allPaths), currentContent, siblingContent);
  return reindexOrdinary(targetIndexPath, allPaths, currentContent);
}
